# Generated by Django 3.2.6 on 2021-10-22 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 10, 22, 9, 52, 59, 128777), verbose_name='Publicado em')),
            ],
        ),
        migrations.AlterField(
            model_name='projetodjango',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 9, 52, 59, 128777), verbose_name='Publicado em'),
        ),
    ]
