# Generated by Django 3.2.6 on 2021-10-22 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211022_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='favmovie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='favmovie',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 10, 0, 37, 225808), verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='projetodjango',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 22, 10, 0, 37, 224806), verbose_name='Publicado em'),
        ),
    ]
